/**
 * <auto-generated>
 * Code generated by luis:generate:ts
 * Tool github: https://github.com/microsoft/botframework-cli
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * </auto-generated>
 */
import {DateTimeSpec, GeographyV2, InstanceData, IntentData, NumberWithUnits, OrdinalV2} from 'botbuilder-ai'

export interface GeneratedIntents {
  Cancel: IntentData
  Confirm: IntentData
  Escalate: IntentData
  ExtractName: IntentData
  FinishTask: IntentData
  GoBack: IntentData
  Help: IntentData
  Logout: IntentData
  None: IntentData
  ReadAloud: IntentData
  Reject: IntentData
  Repeat: IntentData
  SelectAny: IntentData
  SelectItem: IntentData
  SelectNone: IntentData
  ShowNext: IntentData
  ShowPrevious: IntentData
  StartOver: IntentData
  Stop: IntentData
}

export interface GeneratedInstance {
  DirectionalReference?: InstanceData[]
  PersonName_Any?: InstanceData[]
  number?: InstanceData[]
  ordinal?: InstanceData[]
  personName?: InstanceData[]
}

export interface GeneratedEntities {
  // Simple entities
  DirectionalReference?: string[]

  // Built-in entities
  number?: number[]
  ordinal?: number[]
  personName?: string[]

  // Lists

  // Regex entities

  // Pattern.any
  PersonName_Any?: string[]

  // Composites
  $instance: GeneratedInstance
}

export interface GeneralLuis {
  text: string
  alteredText?: string
  intents: GeneratedIntents
  entities: GeneratedEntities
  [propName: string]: any
}
