/**
* <auto-generated>
* Code generated by LUISGen
* Tool github: https://github.com/microsoft/botbuilder-tools
* Changes may cause incorrect behavior and will be lost if the code is
* regenerated.
* </auto-generated>
*/ 
import {DateTimeSpec, GeographyV2, IntentData, InstanceData, NumberWithUnits, OrdinalV2} from 'botbuilder-ai';

export interface _Intents { 
    Sample: IntentData;
    None: IntentData;
};

export interface _Instance {
}

export interface _Entities {
    $instance : _Instance;
}

export interface skillSampleLuis {
    text: string;
    alteredText?: string;
    intents: _Intents;
    entities: _Entities;
    [propName: string]: any;
}
